os: linux
files:
  - source: source
    destination: /home/dkydev_com/webapp/
permissions:
  - object: /home/dkydev_com/webapp/
    pattern: "*"
    owner: dkydev_com
    group: dkydev_com
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root