version: 0.1
os: linux
files:
  - source: /
    destination: /home/dkydev_com/webapp/
permissions:
  - object: /home/dkydev_com/webapp/
    owner: dkydev_com
    group: dkydev_com
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/clean
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

